route:
  receiver: "discord"

receivers:
  - name: "discord"
    discord_configs:
      - webhook_url : "https://discordapp.com/api/webhooks/1502939756265214002/vuVbX0Ir-5liTWie25jnXun2NGrQ7tMw5CRlup0vkGbRZbj2HB7zLMcT5W7nq_751i7H"
        send_resolved: true
        title: '{{ .Status | toUpper }} {{ .CommonLabels.alertname }}'
        message: '{{ range .Alerts }}{{ .Annotations.summary }} - {{ .Annotations.description }}{{ end }}'


