events {}

http {

  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;  

  map $http_user_agent $bad_bot {
      default 0;

      ~*sqlmap 1;
      ~*nikto 1;
      ~*scanner 1;
      ~*curl 1;
  }

  upstream app_backend {
    server app1:80 max_fails=3 fail_timeout=10s;
    server app2:80 backup;
  }

   
  server {
    listen 80;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    server_tokens off;

    limit_req_status 429;

    location / {

      if ($bad_bot) {
         return 403;
      }

      proxy_pass http://app_backend;
      add_header X-Backend $upstream_addr;

      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "no-referrer-when-downgrade" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

      limit_req zone=api_limit burst=10 nodelay;

    }

    location /api/ {
      proxy_pass http://app3:80/;
    }
  }
}
