apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-nginx
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - image: nginx:1.27
        name: nginx
        resources: {}
status: {}
