name: Deploy to VPS

on:
  push:
    branches:
      -master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        user: appleboy/ssh-action@v1.0.3
        with:
          host: 49.12.244.57
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/compose-test/multi-app
            git pull
            docker-compose up -d --force-recreate
